"""governance schema

Revision ID: 51adc5dbfca5
Revises: 5c3c104bde31
Create Date: 2026-09-13 05:57:56.394011
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '51adc5dbfca5'
down_revision: str | None = '5c3c104bde31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_uid', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_APPROVAL', 'SUCCEEDED', 'FAILED', 'COMPENSATED', name='run_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoint_seq', sa.Integer(), nullable=False),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waiting_ref', sa.String(length=64), nullable=True),
    sa.Column('approved_seqs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('step_budget', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('token_used', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uid')
    )
    op.create_index('ix_agent_run_claimable', 'agent_run', ['status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_run_lease_expires_at'), 'agent_run', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_run_lease_owner'), 'agent_run', ['lease_owner'], unique=False)
    op.create_index(op.f('ix_agent_run_status'), 'agent_run', ['status'], unique=False)
    op.create_index(op.f('ix_agent_run_trace_id'), 'agent_run', ['trace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('run_uid', sa.String(length=36), nullable=True),
    sa.Column('step_seq', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCEEDED', 'FAILED', name='audit_outcome', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_run_uid'), 'audit_log', ['run_uid'], unique=False)
    op.create_index(op.f('ix_audit_log_tool_name'), 'audit_log', ['tool_name'], unique=False)
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('run_uid', sa.String(length=36), nullable=False),
    sa.Column('args_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('IN_FLIGHT', 'SUCCEEDED', 'FAILED', name='idempotency_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_key_run_uid'), 'idempotency_key', ['run_uid'], unique=False)
    op.create_index(op.f('ix_idempotency_key_tool_name'), 'idempotency_key', ['tool_name'], unique=False)
    op.create_table('agent_step',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EXECUTE', 'APPROVAL', name='step_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='step_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_agent_step_run_seq')
    )
    op.create_index(op.f('ix_agent_step_idempotency_key'), 'agent_step', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_agent_step_run_id'), 'agent_step', ['run_id'], unique=False)

    # 审计表的不可变性交给数据库,而不是靠「大家记得别改」。
    # 应用层写错一行代码就能删掉历史 —— 那是审计最大的失败模式。
    # 这里是冻结副本;应用侧同一份在 guardrail_api/governance/audit_ddl.py(测试用)。
    op.execute(
        """
        CREATE OR REPLACE FUNCTION guardrail_audit_log_immutable()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log 是追加写表,不允许 % 操作', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION guardrail_audit_log_immutable();
        """
    )
    # TRUNCATE 不触发行级触发器,单独堵住
    op.execute(
        """
        CREATE TRIGGER audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION guardrail_audit_log_immutable();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log')
    op.execute('DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log')
    op.execute('DROP FUNCTION IF EXISTS guardrail_audit_log_immutable()')
    op.drop_index(op.f('ix_agent_step_run_id'), table_name='agent_step')
    op.drop_index(op.f('ix_agent_step_idempotency_key'), table_name='agent_step')
    op.drop_table('agent_step')
    op.drop_index(op.f('ix_idempotency_key_tool_name'), table_name='idempotency_key')
    op.drop_index(op.f('ix_idempotency_key_run_uid'), table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tool_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_run_uid'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_run_trace_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_status'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_lease_owner'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_lease_expires_at'), table_name='agent_run')
    op.drop_index('ix_agent_run_claimable', table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
