"""business schema

Revision ID: 5c3c104bde31
Revises: 
Create Date: 2026-09-13 04:05:13.978979
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5c3c104bde31'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Enum('NORMAL', 'VIP', name='customer_tier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON_SALE', 'OFF_SHELF', name='product_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=32), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_qty >= 0', name='ck_inventory_available_non_negative'),
    sa.CheckConstraint('reserved_qty <= available_qty', name='ck_inventory_reserved_within_available'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'SHIPPED', 'COMPLETED', 'CANCELLED', name='order_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('total_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('receiver_name', sa.String(length=64), nullable=False),
    sa.Column('receiver_phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table('aftersales_ticket',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('REFUND', 'RETURN', 'EXCHANGE', name='ticket_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REFUNDED', 'CLOSED', name='ticket_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('refund_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_by', sa.String(length=64), nullable=True),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_index(op.f('ix_aftersales_ticket_customer_id'), 'aftersales_ticket', ['customer_id'], unique=False)
    op.create_index(op.f('ix_aftersales_ticket_order_id'), 'aftersales_ticket', ['order_id'], unique=False)
    op.create_index(op.f('ix_aftersales_ticket_status'), 'aftersales_ticket', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aftersales_ticket_status'), table_name='aftersales_ticket')
    op.drop_index(op.f('ix_aftersales_ticket_order_id'), table_name='aftersales_ticket')
    op.drop_index(op.f('ix_aftersales_ticket_customer_id'), table_name='aftersales_ticket')
    op.drop_table('aftersales_ticket')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###

